---
- name: Install PostgreSQL 16 from APT
  apt:
    name:
    - postgresql-{{ postgres_version }}
    - python3-psycopg2
    - libpq-dev
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is running and enabled
  service:
    name: postgresql
    state: started
    enabled: true

- name: Configure listen_addresses
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '{{ postgres_listen_addresses }}'"
  notify: Restart PostgreSQL

- name: Allow all hosts in pg_hba.conf
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    line: "host    all             all             0.0.0.0/0               md5"
    insertafter: EOF
  notify: Restart PostgreSQL
