all:
  children:
    db_servers:
      children:
        master:
          hosts:
            db1:
              ansible_host: <master_ip>
              ansible_user: ubuntu
        replica:
          hosts:
            db2:
              ansible_host: <replica_ip>
              ansible_user: ubuntu
